force-app/main/default/objects/Hiring_Team__c/Hiring_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object used to as junction between Job Application and Contact. Used to associate multiple contacts with a Job Application.</description>
    <label>Hiring Team</label>
    <nameField>
        <displayFormat>HT-{0000}</displayFormat>
        <label>Hiring Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiring Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hiring Teams</relationshipLabel>
    <relationshipName>Hiring_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hiring_Team__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Hiring Teams</relationshipLabel>
    <relationshipName>Hiring_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hiring_Team__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to track Job Applications through various stages of the process.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to store primary contact for the job application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</description>
    <inlineHelpText>Primary Contact for application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HiringTeamHandler.cls
public with sharing class HiringTeamHandler extends TriggerHandler{

    private List<Hiring_Team__c> newHiringTeam;
    private List<Hiring_Team__c> oldHiringTeam;
    private Map<Id, Hiring_Team__c> newHiringTeamMap;
    private Map<Id, Hiring_Team__c> oldHiringTeamMap;
    
    public HiringTeamHandler() {

        this.newHiringTeam = (List<Hiring_Team__c>) Trigger.new;
        this.oldHiringTeam = (List<Hiring_Team__c>) Trigger.old;
        this.newHiringTeamMap = (Map<Id, Hiring_Team__c>) Trigger.newMap;
        this.oldHiringTeamMap = (Map<Id, Hiring_Team__c>) Trigger.oldMap;
    }

    public override void afterInsert(){
        List<Job_Application__c> jobAppsToUpdate = setApplicationPrimaryContact(newHiringTeam);
        
        update jobAppsToUpdate;
    }

    public override void afterUpdate(){
        List<Job_Application__c> jobAppsToUpdate = new List<Job_Application__c>();
        List<Job_Application__c> setAppPrimaryContact = setApplicationPrimaryContact(newHiringTeam);
        List<Job_Application__c> removeAppPrimaryContact = removePrimaryContact(newHiringTeamMap,oldHiringTeamMap);
        jobAppsToUpdate.addAll(setAppPrimaryContact);
        jobAppsToUpdate.addAll(removeAppPrimaryContact);
       
        update jobAppsToUpdate;
    }

    public static List<Job_Application__c> setApplicationPrimaryContact(List<Hiring_Team__c> newHiringTeam){
        //Create map of Job Application Ids and Primary Contact Ids
        Map<Id,Id> jobAppIdToPrimaryContactIdMap = new Map<Id,Id>();
        //Create List of Job App Ids to be used in SOQL Query
        List<Id> jobAppIds = new List<Id>();
       
        //Identify Hiring Team records set as Primary Contacts and add to map
        for(Hiring_Team__c teamMember :newHiringTeam){
            if(teamMember.Primary_Contact__c == true){
                jobAppIdToPrimaryContactIdMap.put(teamMember.Job_Application__c,teamMember.Contact__c);
                jobAppIds.add(teamMember.Job_Application__c);
            }
        }
        
        //Create List of Job Applications to update
        List<Job_Application__c> jobAppsToUpdate = [SELECT Id, Primary_Contact__c FROM Job_Application__c WHERE Id IN :jobAppIds];
        for(Job_Application__c jobApp :jobAppsToUpdate){
            jobApp.Primary_Contact__c = jobAppIdToPrimaryContactIdMap.get(jobApp.Id);
        }
        
        return jobAppsToUpdate;
    }

    public static List<Job_Application__c> removePrimaryContact(Map<Id, Hiring_Team__c> newHiringTeamMap, Map<Id, Hiring_Team__c> oldHiringTeamMap){
        List<Id> jobAppIds = new List<Id>();
        for(Hiring_Team__c teamMember :newHiringTeamMap.values()){
            if(oldHiringTeamMap.get(teamMember.Id).Primary_Contact__c == true && teamMember.Primary_Contact__c == false){
                jobAppIds.add(teamMember.Job_Application__c);
            }
        }
        List<Job_Application__c> jobAppUpdates = [SELECT Id, Primary_Contact__c FROM Job_Application__c WHERE Id IN :jobAppIds];
        for(Job_Application__c jobApp :jobAppUpdates){
            jobApp.Primary_Contact__c = null;
        }
        return jobAppUpdates;
    }

}