force-app/main/default/objects/Hiring_Team__c/Hiring_Team__c.object-meta.xml
<CustomObject>
    <description>Custom object used to as junction between Job Application and Contact. Used to associate multiple contacts with a Job Application.</description>
    <label>Hiring Team</label>
    <nameField>
        <displayFormat>HT-{0000}</displayFormat>
        <label>Hiring Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiring Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hiring Teams</relationshipLabel>
    <relationshipName>Hiring_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hiring_Team__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Hiring Teams</relationshipLabel>
    <relationshipName>Hiring_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hiring_Team__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to track Job Applications through various stages of the process.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account record storing information about the company.</description>
    <inlineHelpText>Select the Company associated with the application.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to store primary contact for the job application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</description>
    <inlineHelpText>Primary Contact for application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Field used to track salary for the position.</description>
    <inlineHelpText>Enter salary for the job.</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary_Type__c.field-meta.xml
<CustomField>
    <fullName>Salary_Type__c</fullName>
    <label>Salary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
                <default>true</default>
                <label>Annual</label>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Tax_Filing_Status__c.field-meta.xml
<CustomField>
    <fullName>Tax_Filing_Status__c</fullName>
    <description>Allows selection of tax filing status to calculate tax withholdings</description>
    <inlineHelpText>Select tax filing status</inlineHelpText>
    <label>Tax Filing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married, filing jointly</fullName>
            </value>
            <value>
                <fullName>Married, filing separately</fullName>
            </value>
            <value>
                <fullName>Head of Household</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Withholding__mdt/Tax_Withholding__mdt.object-meta.xml
<CustomObject>
    <label>Tax Withholding</label>
    <pluralLabel>Tax Withholdings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Withholding__mdt/fields/Filing_Status__c.field-meta.xml
<CustomField>
    <fullName>Filing_Status__c</fullName>
    <label>Filing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married, filing jointly</fullName>
            </value>
            <value>
                <fullName>Married, filing separately</fullName>
            </value>
            <value>
                <fullName>Head of Household</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Withholding__mdt/fields/Maximum_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Amount__c</fullName>
    <label>Maximum Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Withholding__mdt/fields/Minimum_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Amount__c</fullName>
    <label>Minimum Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Withholding__mdt/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Withholding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Federal Income</fullName>
                <default>true</default>
                <label>Federal Income</label>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Standard Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationHandler.cls
public with sharing class JobApplicationHandler extends TriggerHandler {

    //Initialize variables 
    private List<Job_Application__c> newJobApplications;
    private List<Job_Application__c> oldJobApplications;
    private Map<Id, Job_Application__c> newJobApplicationMap;
    private Map<Id, Job_Application__c> oldJobApplicationMap;

    //Setting variables with values from trigger
    public JobApplicationHandler() {

        this.newJobApplications = (List<Job_Application__c>) Trigger.new;
        this.oldJobApplications = (List<Job_Application__c>) Trigger.old;
        this.newJobApplicationMap = (Map<Id, Job_Application__c> ) Trigger.newMap;
        this.oldJobApplicationMap = (Map<Id, Job_Application__c> ) Trigger.oldMap;
    }

    public override void beforeInsert(){
        setPrimaryContact(newJobApplications);

    }

    public override void afterInsert(){
        List<Hiring_Team__c> hiringTeamList = createMissingHiringTeam(newJobApplications);
        TriggerHandler.bypass('HiringTeamHandler');
        Database.insert (hiringTeamList, AccessLevel.SYSTEM_MODE);
        TriggerHandler.clearAllBypasses();
        //Method to create Tasks for the Job Application record based on the Status of the Application
        JobApplicationStatusHelper.tasksBasedOnStatus(newJobApplications, oldJobApplicationMap);
    }

    public override void afterUpdate(){
        //The below method creates Tasks for Job Application record based on the Status of the Application
        JobApplicationStatusHelper.tasksBasedOnStatus(newJobApplications, oldJobApplicationMap);
    }

    public static void setPrimaryContact(List<Job_Application__c> newJobApplications){
        //Initialize list of Account Ids and map of Account Ids by Job Application Ids and populate the list and map
        List<Id> accountIdList = new List<Id>();
        Map<Id,Id> accountIdByJobAppIdMap = new Map<Id,Id>();
        for(Job_Application__c jobApp :newJobApplications){
            accountIdList.add(jobApp.Company__c);
            accountIdByJobAppIdMap.put(jobApp.Id, jobApp.Company__c);
        }
        //Use Account Id list to query list of Contact
        List<Contact> contactList = [SELECT Id, Name, CreatedDate,AccountId FROM Contact WHERE AccountId IN :accountIdList Order By CreatedDate ASC];
        //Initialize map of Contact Ids by Account Ids and populate the map
        Map<Id,Id> contactIdByAccountIdMap = new Map<Id,Id>();
        for(Contact con :contactList){
            if(!contactIdByAccountIdMap.containsKey(con.AccountId)){
                contactIdByAccountIdMap.put(con.AccountId,con.Id);
            }
        }

        /**For each Job Application if Primary Contact is null, the Job Application is in the Account Id map, 
        and the Account is in the Contact Id map, set the Primary Contact
        **/
        for(Job_Application__c jobApp :newJobApplications){
            if(jobApp.Primary_Contact__c == null && accountIdByJobAppIdMap.containsKey(jobApp.Id) && contactIdByAccountIdMap.containsKey(jobApp.Company__c)){
                jobApp.Primary_Contact__c = contactIdByAccountIdMap.get(jobApp.Company__c);
            }
        }
    }

    public static List<Hiring_Team__c> createMissingHiringTeam(List<Job_Application__c> newJobApplications){
        //Initialze lists of Hiring Team and Job Application Ids
        List<Hiring_Team__c> hiringTeamList = new List<Hiring_Team__c>();
        List<Id> jobAppId = new List<Id>();
        //Initialize map of Contacts by Job Application Id 
        Map<Id,Id> contactByJobAppIdMap = new Map<Id,Id>();
        //Populate the Job Application Id list and map
        for(Job_Application__c jobApp :newJobApplications){
            if(jobApp.Primary_Contact__c != null){
                jobAppId.add(jobApp.Id);
                contactByJobAppIdMap.put(jobApp.Id, jobApp.Primary_Contact__c);
            }
        }

        for(Job_Application__c jobApp :newJobApplications){
            if(jobApp.Primary_Contact__c == null){
                continue;
            }
            Hiring_Team__c newHiringTeam = new Hiring_Team__c (Job_Application__c = jobApp.Id, Contact__c = contactByJobAppIdMap.get(jobApp.Id), Primary_Contact__c = true);
            hiringTeamList.add(newHiringTeam);
        }
        return hiringTeamList;
    }

    public static void taxWithholdingCalculator(List<Job_Application__c> newJobApplications){
        //Assign tax filing status
        List<String> filingStatus = new List<String>();
        List<Decimal> salaryAmount = new List<Decimal>();
        Integer weeklyHours = 40;
        Integer weeksInYear = 52;
        for(Job_Application__c jobApp :newJobApplications){
            if(jobApp.Tax_Filing_Status__c != null){
                filingStatus.add(jobApp.Tax_Filing_Status__c);
            }
            salaryAmount.add(annualSalaryCalculator(jobApp));
        }
        //Get Tax rate data
        List<Tax_Withholding__mdt> federalTaxRates = [SELECT Id, Tax_Rate__c, Type__c, Filing_Status__c, Minimum_Amount__c, Maximum_Amount__c 
                                                FROM Tax_Withholding__mdt
                                                WHERE Filing_Status__c IN :filingStatus
                                                Order By Tax_Rate__c ASC];
        Tax_Withholding__mdt socialSecurityRateRecord = [SELECT Id, Tax_Rate__c, Type__c, Filing_Status__c, Minimum_Amount__c, Maximum_Amount__c 
                                                    FROM Tax_Withholding__mdt
                                                    WHERE Type__c = 'Social Security'];
        Tax_Withholding__mdt medicareRateRecord = [SELECT Id, Tax_Rate__c, Type__c, Filing_Status__c, Minimum_Amount__c, Maximum_Amount__c 
                                                    FROM Tax_Withholding__mdt
                                                    WHERE Type__c = 'Medicare'];
        Decimal socialSecurityRate = socialSecurityRateRecord.Tax_Rate__c;
        Decimal medicareRate = medicareRateRecord.Tax_Rate__c;
        
        //Initial map of Job Applications By Id and populate the map
        Map<Id,Job_Application__c> jobApplictionByIdMap = new Map<Id,Job_Application__c>();
        for(Job_Application__c jobApp :newJobApplications){
            if(!jobApplictionByIdMap.containsKey(jobApp.Id)){
                jobApplictionByIdMap.put(jobApp.Id, jobApp);
            }
        }

        for(Job_Application__c jobApp :newJobApplications){
            Decimal annualSalary = annualSalaryCalculator(jobApp);
            Decimal remainingSalary = annualSalary;
            Decimal socialSecurityWithheld = annualSalary * socialSecurityRate;
            Decimal medicareWithheld = annualSalary * medicareRate;
            Decimal taxWithheld = medicareWithheld + socialSecurityWithheld;
            for(Tax_Withholding__mdt taxRate :federalTaxRates){
                Decimal rate = taxRate.Tax_Rate__c / 100;
                if(annualSalary != null && annualSalary >= taxRate.Minimum_Amount__c && annualSalary <= taxRate.Maximum_Amount__c){
                    taxWithheld = annualSalary * rate;
                    remainingSalary -= taxWithheld;
                }
            }
        }
    }

    public static Decimal annualSalaryCalculator(Job_Application__c jobApp){
        Decimal annualSalary = 0;
        Integer weeklyHours = 40;
        Integer weeksInYear = 52;
        if(jobApp.Salary__c != null && jobApp.Salary_Type__c == 'Annual'){
            annualSalary = jobApp.Salary__c;
        }
        else if (jobApp.Salary__c != null && jobApp.Salary_Type__c == 'Hourly'){
            annualSalary = (jobApp.Salary__c * weeklyHours) * weeksInYear;
        }
        else if (jobApp.Salary__c != null && jobApp.Salary_Type__c == 'Weekly'){
            annualSalary = jobApp.Salary__c * weeksInYear;
        }

        return annualSalary;
    }
}