force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to track Job Applications through various stages of the process.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Stores the date candidate applied for the job.</description>
    <inlineHelpText>Enter date applied for the job.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account record storing information about the company.</description>
    <inlineHelpText>Select the Company associated with the application.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Long text area for entering job description.</description>
    <inlineHelpText>Enter job description</inlineHelpText>
    <label>Description</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <description>Field used to select a date on which to follow up on job application.</description>
    <inlineHelpText>Enter date to follow up on job application.</inlineHelpText>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting_URL__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting_URL__c</fullName>
    <description>URL for tracking the job posting URL</description>
    <inlineHelpText>Enter URL for job posting.</inlineHelpText>
    <label>Job Posting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>This field is use to track if the job is Contract, Full-time, Part-time, Temporary, etc.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Field used to describe location type for job.</description>
    <inlineHelpText>Select if job is on-site, hybrid, or remote.</inlineHelpText>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On-Site</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>Field used to store the position name or title for the job.</description>
    <inlineHelpText>Enter the position name or job title.</inlineHelpText>
    <label>Position/Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to store primary contact for the job application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</description>
    <inlineHelpText>Primary Contact for application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Rating_Scale__c.field-meta.xml
<CustomField>
    <fullName>Rating_Scale__c</fullName>
    <description>Field used to attractiveness of job on a scale of 1-5.</description>
    <inlineHelpText>Select attractiveness of job on a scale of 1-5.</inlineHelpText>
    <label>Rating Scale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Field used to track salary for the position.</description>
    <inlineHelpText>Enter salary for the job.</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary_Type__c.field-meta.xml
<CustomField>
    <fullName>Salary_Type__c</fullName>
    <label>Salary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
                <default>true</default>
                <label>Annual</label>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/TestDataFactory_20240727135633.cls
/**
 * @description       : 
 * @author            : Riley Meyer
 * @group             : 
 * @last modified on  : 07-27-2024
 * @last modified by  : Riley Meyer
**/
@IsTest
public class TestDataFactory {

    @TestVisible
    private static List<User> createUsers(Integer numRecords) {
        List<User> users = new List<User>();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

        for (Integer i = 0; i < numRecords; i++) {
            User u = new User();
            u.Alias = 'user' + i;
            u.Email='testemail' + i + '@cloudsmiths.com';
            u.EmailEncodingKey='UTF-8';
            u.FirstName='Test' + i;
            u.LastName='User' + i;
            u.LanguageLocaleKey='en_US'; 
            u.LocaleSidKey='en_US';
            u.ProfileId = p.Id; 
            u.TimeZoneSidKey='America/Los_Angeles';
            u.UserName='testemail' + i + '@cloudsmiths.com';
            users.add(u);
        }
        System.debug('Number of Users to Inser: ' + users);
        Database.insert(users, AccessLevel.SYSTEM_MODE);

        // Prevents Mixed DML Operation Error
        System.runAs(new User(Id = Userinfo.getUserId())) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Job_Application_Permission_Set'];
            List<PermissionSetAssignment> permAssignments = new List<PermissionSetAssignment>();
            for (User u : users) {
                PermissionSetAssignment psa = new PermissionSetAssignment();
                psa.AssigneeId = u.Id;
                psa.PermissionSetId = ps.Id;
                permAssignments.add(psa);
            }
        Database.insert(permAssignments, AccessLevel.SYSTEM_MODE);
        }

        return users;
    }

    @TestVisible
    private static List<Account> createAccounts(Integer numRecords) {
        List<Account> accounts = new List<Account>();

        for (Integer i = 0; i < numRecords; i++) {
            Account a = new Account();
            a.Name = 'Test Account ' + i;
            accounts.add(a);
        }
        Database.insert(accounts, AccessLevel.SYSTEM_MODE);

        return accounts;
    }

    @TestVisible
    private static List<Contact> createContacts(List<Account> accounts, Integer numRecords) {
        List<Contact> contacts = new List<Contact>();

        for (Integer i = 0; i < numRecords; i++) {
            Contact c = new Contact();
            c.FirstName = 'Test';
            c.LastName = 'Contact ' + i;
            c.AccountId = accounts[i].Id;
            c.Email = 'testcontact' + i + '@cloudsmiths.com';
            contacts.add(c);
        }
        Database.insert(contacts, AccessLevel.SYSTEM_MODE);

        return contacts;
    }

    @TestVisible
    private static List<Job_Application__c> createJobApplications(List<User> users, List<Account> accounts, List<Contact> contacts, Integer numRecords) {
        List<Job_Application__c> jobApps = new List<Job_Application__c>();

        for (Integer i = 0; i < numRecords; i++) {
            Job_Application__c j = new Job_Application__c();
            j.OwnerId = users[i].Id;
            j.Status__c = 'Saved';
            j.Company__c = accounts[i].Id;
            j.Primary_Contact__c = contacts[i].Id;
            j.Position_Title__c = 'Developer' + i + 'at' + accounts[i].Name;
            j.Description__c = 'Dummy Job Description';
            j.Job_Posting_URL__c = 'https://jooble.org';
            if (i < 15) {
                j.Job_Type__c = 'Full-time';
                j.Salary__c = 150;
                j.Salary_Type__c = 'Annual';
                j.Location__c = 'Miami, FL';
                j.Location_Type__c = 'On-Site';
                j.Application_Date__c = Date.today();
                j.Follow_Up_Date__c = null;
                j.Rating_Scale__c = '2';
            } else if (i < 200) {
                j.Job_Type__c = 'Part-time';
                j.Salary__c = 58;
                j.Salary_Type__c = 'Hourly';
                j.Location__c = 'Omaha, NE';
                j.Location_Type__c = 'Hybrid';
                j.Application_Date__c = Date.today().addDays(-40);
                j.Follow_Up_Date__c = Date.today().addDays(-25);
                j.Rating_Scale__c = '3';
            } else {
                j.Job_Type__c = 'Contract';
                j.Salary__c = 3000;
                j.Salary_Type__c = 'Weekly';
                j.Location__c = 'Houston, TX';
                j.Location_Type__c = 'Remote';
                j.Application_Date__c = Date.today().addDays(-60);
                j.Follow_Up_Date__c = Date.today().addDays(-45);
                j.Rating_Scale__c = '5';
            }
            jobApps.add(j);
        }
        Database.insert(jobApps, AccessLevel.SYSTEM_MODE);

        for (Job_Application__c jobApp : jobApps) {
            if (jobApp.Application_Date__c == Date.today()) {
                Test.setCreatedDate(jobApp.Id, Date.today().addDays(-35));
            } else if (jobApp.Application_Date__c == Date.today().addDays(-40)) {
                Test.setCreatedDate(jobApp.Id, Date.today().addDays(-45));
            } else if (jobApp.Application_Date__c == Date.today().addDays(-60)) {
                Test.setCreatedDate(jobApp.Id, Date.today().addDays(-70));
            } else {
                Test.setCreatedDate(jobApp.Id, Date.today());
            }
        }

        return jobApps;
    }

    @TestVisible
    private static List<Event> createInterviews(List<Job_Application__c> jobApps, Integer numRecords) {
        List<Event> interviews = new List<Event>();
        for (Integer i = 0; i < numRecords; i++) {
            Event e = new Event();
            e.OwnerId = jobApps[i].OwnerId;
            e.Location = jobApps[i].Location__c;
            e.Subject = 'Interview';
            e.WhoId = jobApps[i].Primary_Contact__c;
            e.WhatId = jobApps[i].Id;
            if (jobApps[i].Application_Date__c == Date.today()) {
                e.Interview_Type__c = 'Screening Interview';
                e.Interview_Format__c = 'Phone';
                e.StartDateTime = DateTime.now().addDays(1);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else if (jobApps[i].Application_Date__c == Date.today().addDays(-40)) {
                e.Interview_Type__c = 'Panel Interview';
                e.Interview_Format__c = 'Video';
                e.StartDateTime = DateTime.now().addDays(-39);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else if (jobApps[i].Application_Date__c == Date.today().addDays(-60)) {
                e.Interview_Type__c = 'Technical Interview';
                e.Interview_Format__c = 'On-Site';
                e.StartDateTime = DateTime.now().addDays(-59);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else {
                e.Interview_Type__c = 'Hiring Manager Interview';
                e.Interview_Format__c = 'On-Site';
                e.StartDateTime = DateTime.now().addDays(i);
                e.EndDateTime = e.StartDateTime.addHours(1);
            }
            interviews.add(e);
        }

        Database.insert(interviews, AccessLevel.SYSTEM_MODE);

        return interviews;
    }

}