force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to track Job Applications through various stages of the process.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Stores the date candidate applied for the job.</description>
    <inlineHelpText>Enter date applied for the job.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to store primary contact for the job application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</description>
    <inlineHelpText>Primary Contact for application. Auto-populated by adding Primary Contact on Hiring Team or by using the first Contact on the associated Account.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

.history/force-app/main/default/classes/InterviewReminderTest_20240726231536.cls
/**
 * @description       : 
 * @author            : Riley Meyer
 * @group             : 
 * @last modified on  : 07-26-2024
 * @last modified by  : Riley Meyer
**/
@IsTest
private class InterviewReminderTest {
    @TestSetup
    static void makeData(){
        Integer numRecords = 250;
        List<User> users = TestDataFactory.createUsers(numRecords);
        List<Account> accounts = TestDataFactory.createAccounts(numRecords);
        List<Contact> contacts = TestDataFactory.createContacts(accounts, numRecords);
        List<Job_Application__c> jobApps = TestDataFactory.createJobApplications(users, accounts, contacts, numRecords);
        List<Event> interviews = TestDataFactory.createInterviews(jobApps, numRecords);

        for (Integer i = 0; i < numRecords; i++) {
            Event e = new Event();
            e.OwnerId = jobApps[i].OwnerId;
            e.Location = jobApps[i].Location__c;
            e.Subject = 'Interview';
            e.WhoId = jobApps[i].Primary_Contact__c;
            e.WhatId = jobApps[i].Id;
            if (jobApps[i].Application_Date__c == Date.today()) {
                e.Interview_Type__c = 'Screening Interview';
                e.Interview_Format__c = 'Phone';
                e.StartDateTime = DateTime.now().addDays(1).addHours(i);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else if (jobApps[i].Application_Date__c == Date.today().addDays(-40)) {
                e.Interview_Type__c = 'Panel Interview';
                e.Interview_Format__c = 'Video';
                e.StartDateTime = DateTime.now().addDays(-39).addHours(i);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else if (jobApps[i].Application_Date__c == Date.today().addDays(-60)) {
                e.Interview_Type__c = 'Technical Interview';
                e.Interview_Format__c = 'On-Site';
                e.StartDateTime = DateTime.now().addDays(-59).addHours(i);
                e.EndDateTime = e.StartDateTime.addHours(1);
            } else {
                e.Interview_Type__c = 'Hiring Manager Interview';
                e.Interview_Format__c = 'On-Site';
                e.StartDateTime = DateTime.now().addDays(i).addHours(i);
                e.EndDateTime = e.StartDateTime.addHours(1);
            }
            interviews.add(e);
        }
        Database.insert(interviews, AccessLevel.SYSTEM_MODE);
    }

}